export const ADMIN_LINKS = [
  { to: '/admin', label: "Vue d'ensemble", end: true },
  { to: '/admin/orders', label: 'Commandes' },
  { to: '/admin/products', label: 'Produits' },
  { to: '/admin/suppliers', label: 'Fournisseurs' },
  { to: '/inventory-sheets', label: 'Stocks Google Sheets' },
  { to: '/integration-logs', label: "Journaux d'intégration" },
  { to: '/category-manager', label: 'Catégories' },
  { to: '/admin/command-center', label: 'Centre de commande' },
  { to: '/warehouse', label: 'Entrepôt' },
  { to: '/support-inbox', label: 'Chat support' },
  { to: '/developers', label: 'Développeurs' },
  { to: '/supplier-portal', label: 'Portail fournisseurs' },
  { to: '/delivery-map', label: 'Carte des livraisons' },
  { to: '/fraud-alerts', label: 'Alertes de fraude' },
  { to: '/admin/returns', label: 'Retours & litiges' },
  { to: '/admin/disputes', label: 'Litiges ouverts' },
  { to: '/dispute-resolution', label: 'Résolution des litiges' },
  { to: '/finance', label: 'Finance' },
  { to: '/pickup-manager', label: 'Points de retrait' },
  { to: '/admin/payouts', label: 'Retraits' },
  { to: '/admin/logistics', label: 'Logistique' },
  { to: '/logistics-rates', label: 'Tarifs logistiques' },
  { to: '/shipping-config', label: 'Configuration livraison' },
  { to: '/logistics-hub', label: 'Hub logistique' },
  { to: '/coverage-map', label: 'Couverture' },
  { to: '/admin/notifications', label: 'Notifications' },
  { to: '/admin/events', label: 'Événements' },
  { to: '/admin/workflows', label: 'Workflows' },
  { to: '/workflow-monitor', label: 'Supervision' },
  { to: '/admin/fraud', label: 'Fraude & risques' },
  { to: '/admin/promotions', label: 'Promotions' },
  { to: '/marketing-analytics', label: 'Marketing' },
  { to: '/platform-analytics', label: 'Analytique plateforme' },
  { to: '/platform-health', label: 'Santé plateforme' },
  { to: '/service-level-monitor', label: 'Niveaux de service' },
  { to: '/admin/users', label: 'Utilisateurs' },
  { to: '/admin/tenants', label: 'Enseignes SaaS' },
  { to: '/admin/compliance', label: 'Conformité' },
  { to: '/security-activity', label: 'Activité de sécurité' },
  { to: '/admin/settings', label: 'Paramètres' },
];

export const SELLER_LINKS = [
  { to: '/seller', label: 'Tableau de bord', end: true },
  { to: '/seller/products', label: 'Produits' },
  { to: '/seller/orders', label: 'Commandes' },
  { to: '/seller/messages', label: 'Messages' },
  { to: '/bulk-orders', label: 'Traitement groupé' },
  { to: '/merchant-disputes', label: 'Litiges' },
  { to: '/dispute-resolution', label: 'Résolution des litiges' },
  { to: '/seller/import', label: 'Import fournisseur' },
  { to: '/bulk-import', label: 'Import CSV' },
  { to: '/seller/wallet', label: 'Portefeuille' },
  { to: '/payout-ledger', label: 'Grand livre' },
  { to: '/seller-reports', label: 'Rapports' },
  { to: '/market-trends', label: 'Tendances' },
  { to: '/tax-reports', label: 'Fiscalité' },
  { to: '/inventory-alerts', label: 'Alertes stock' },
  { to: '/payout-history', label: 'Retraits' },
  { to: '/payout-settings', label: 'Paiement' },
  { to: '/data-export', label: 'Export' },
  { to: '/seller/settings', label: 'Boutique' },
  { to: '/subscription-plans', label: 'Abonnement' },
];