export const ADMIN_LINKS = [
  { to: '/admin', label: "Vue d'ensemble", end: true },
  { to: '/admin/orders', label: 'Commandes' },
  { to: '/admin/products', label: 'Produits' },
  { to: '/admin/suppliers', label: 'Fournisseurs' },
  { to: '/admin/returns', label: 'Retours & litiges' },
  { to: '/admin/disputes', label: 'Litiges ouverts' },
  { to: '/admin/payouts', label: 'Retraits' },
  { to: '/admin/logistics', label: 'Logistique' },
  { to: '/admin/notifications', label: 'Notifications' },
  { to: '/admin/events', label: 'Événements' },
  { to: '/admin/workflows', label: 'Workflows' },
  { to: '/admin/fraud', label: 'Fraude & risques' },
  { to: '/admin/promotions', label: 'Promotions' },
  { to: '/marketing-analytics', label: 'Marketing' },
  { to: '/admin/users', label: 'Utilisateurs' },
  { to: '/admin/tenants', label: 'Enseignes SaaS' },
  { to: '/admin/compliance', label: 'Conformité' },
  { to: '/admin/settings', label: 'Paramètres' },
];

export const SELLER_LINKS = [
  { to: '/seller', label: 'Tableau de bord', end: true },
  { to: '/seller/products', label: 'Produits' },
  { to: '/seller/orders', label: 'Commandes' },
  { to: '/seller/import', label: 'Import fournisseur' },
  { to: '/seller/wallet', label: 'Portefeuille' },
  { to: '/payout-history', label: 'Retraits' },
  { to: '/payout-settings', label: 'Paiement' },
  { to: '/data-export', label: 'Export' },
  { to: '/seller/settings', label: 'Boutique' },
];